M48
; DRILL file KiCad 10.0.1 date 2026-06-06T16:23:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-06T16:23:08-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X55.0Y-55.0
X55.0Y-95.0
X135.0Y-55.0
X135.0Y-95.0
T2
X64.81Y-78.57
M30
